name: ESLint

on:
  push:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: "🛸 install eslint plugins"
        run: npm i --no-fund --no-audit

      - name: "🔍 lint code"
        run: npx eslint --ext .html,.js . --report-unused-disable-directives
